#// Запросы для ручного тестирования api-enddpoints
@ApiService_HostAddress = http://localhost:5010

GET {{ApiService_HostAddress}}/api/files
Accept: application/json

###

POST {{ApiService_HostAddress}}/api/files/archive
Content-Type: application/json

{
    "fileNames": [
        "file1",
        "file2",
        "file3"
    ]
}
###

#// Вместо processId - полученный идентификатор из POST запроса
GET {{ApiService_HostAddress}}/api/files/archive/processId
Accept: application/json

###

#// Вместо processId - полученный идентификатор из POST запроса
GET {{ApiService_HostAddress}}/api/files/archive/processId/download
Accept: application/json
#// curl http://localhost:5010/api/files/archive/723179/download --output archive.zip
###